### ISSUE TITLE
Login authentication error 403

### ISSUE THREAD

**Issue by SailingGreg** [KaSroka/Toshiba-AC-control#49] opened 2024-05-22 09:10 UTC
I was unable to authenticate via python although curl with the same user credentials worked. Issue turned out to be that requests() was specifying the user agent as the following and this was getting bounced by the azure gateway 

'User-Agent': 'python-requests/2.21.0'

Specifying the user agent in the headers addresses the issue

headers = {
    "Content-Type": "application/json",
    "User-Agent": "curl/7.64.0"
}

See https://stackoverflow.com/questions/65837008/what-happens-if-i-dont-specify-the-user-agent-in-requests-get

**Comment by KaSroka** [comment] 2024-08-12 18:02
Thank you for reporting and investigation, this was fixed in v0.3.5

**Closed by KaSroka** 2024-08-12 18:02 UTC

**Comment by KaSroka** [comment] 2024-08-12 22:58
Actually this 403 was not caused by user-agent header. It was caused by rate limiting/DDoS protection on the HTTP endpoint. It is fixed in latest version.
